security:
  basic:
    enabled: false
management:
  security:
    enabled: false
spring:
  jpa:
    hibernate:
      ddl-auto: create
---
spring:  
  profiles: jiu-jitsu
dojo:
  discipline: bjj
---
spring:  
  profiles: judo
dojo:
  discipline: judo