platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: latest

inputs:
  - name: resource-dojo

outputs:
  - name: output

run:
  path: sh
  args:
    - resource-dojo/ci/tasks/maven-package.sh
